version: "2"
services:
  app:
    image: golang:1.14.3
    ports:
      - "3005:3005"
    volumes:
      - .:/go/src/abgenius
    working_dir: /go/src/abgenius
    command: bash -c "go get github.com/golang/dep/cmd/dep && dep ensure && go build . && ./root-cellar"
    links:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo
    restart: unless-stopped
  mongo:
    image: mongo
    volumes:
      - ./mdata:/data/db
    restart: unless-stopped
volumes:
  mdata: